# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish apialerts-js

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - name: Send Build Alert
        run: node node sample/onGitHubAction.js --message="Javascript - Build for Publish Success" --tags="CI/CD,JS,Build" --link="https://github.com/apialerts/apialerts-js/actions"
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Send Publish Alert
        run: node node sample/onGitHubAction.js --message="Javascript - NPM Publish Success" --tags="CI/CD,JS,Deploy" --link="https://github.com/apialerts/apialerts-js/actions"
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}