name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Send Build Alert
        run: node node sample/GitHubAction.js --release
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}

  publish-npm:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install Node Dependencies
        run: npm ci
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Send Publish Alert
        run: node node sample/GitHubAction.js --publish
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}