name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Node Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm test
      - name: Send PR Build Alert
        run: npx tsx sample/run.ts --build
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}